cartoonproject/cartoonapp/urls.py
from django.urls import path,include
from. import views
app_name='cartoonapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('cartoon/<int:cartoon_id>/',views.detail,name='detail'),
    path('add/',views.add_cartoon,name='add_cartoon'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

cartoonproject/cartoonproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("cartoonapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cartoonproject/cartoonapp/models.py
from django.db import models

# Create your models here.
class Cartoon(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

cartoonproject/cartoonapp/forms.py
from django import forms
from.models import Cartoon

class CartoonForm(forms.ModelForm):
    class Meta:
        model=Cartoon
        fields=['name','desc','year','img']

cartoonproject/cartoonapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Cartoon
from . forms import CartoonForm
# Create your views here.
def index(request):
    cartoon=Cartoon.objects.all()
    context={
        'cartoon_list':cartoon
    }
    return render(request,'index.html',context)
def detail(request,cartoon_id):
    cartoon=Cartoon.objects.get(id=cartoon_id)
    return render(request,"detail.html",{'cartoon':cartoon})
def add_cartoon(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        cartoon=Cartoon(name=name,desc=desc,year=year,img=img)
        cartoon.save()

    return render(request,'add.html')

def update(request,id):
    cartoon=Cartoon.objects.get(id=id)
    form=CartoonForm(request.POST or None, request.FILES,instance=cartoon)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'cartoon':cartoon})
def delete(request,id):
    if request.method=='POST':
        cartoon=Cartoon.objects.get(id=id)
        cartoon.delete()
        return redirect('/')
    return render(request,'delete.html')

cartoonproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {%csrf_token %}
    <input type="text" name="name" placeholder="Enter Your cartoon name ">
    <input type="text" name="desc" placeholder="Enter Your cartoon description ">
    <input type="text" name="year" placeholder="Enter Your cartoon year ">
    <input type="file" name="img">
    <input type="submit">
</form>
{% endblock %}

cartoonproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Cartoon Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

cartoonproject/templates/delete.html
<form method="POST">

  {% csrf_token %}
  Are You want to delete this cartoon ?
  <input type="submit">
</form>

cartoonproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<img src="{{cartoon.img.url}}" width="100" height="100"
{{cartoon.name}}<br>
{{cartoon.desc}}<br>
{{cartoon.year}}<br>
<a class="btn btn-warning" href="{% url 'cartoonapp:update' cartoon.id %}">update</a><br>
<a class="btn btn-danger" href="{% url 'cartoonapp:delete' cartoon.id %}">delete</a><br>

{% endblock %}

cartoonproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
</form>

cartoonproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
{% for i in cartoon_list %}
<img src="{{i.img.url}}" width="100" height="100">
<a href="{% url 'cartoonapp:detail' i.id %}">{{i.name}}<br>
{% endfor %}
{% endblock %}